let employees = [
  {
    id: 1,
    name: "Kiran",
    date: "01/01/2025",
    email: "kiran@gmail.com",
    phone: "9876543211",
    nationality: "Indian",
    gender: "Male",
    age: 25,
    status: "Active",
    hire: "Full-time",
    skills: "Machine Learning, Python, TensorFlow",
    address: "Ahmedabad, India",
    photo: "https://via.placeholder.com/150?text=Kiran"
  },
  {
    id: 2,
    name: "Vishnu",
    date: "20/07/2020",
    email: "vishnu@gmail.com",
    phone: "9876543212",
    nationality: "Indian",
    gender: "Male",
    age: 30,
    status: "Active",
    hire: "Full-time",
    skills: "DevOps, AWS, Docker",
    address: "Pune, India",
    photo: "https://via.placeholder.com/150?text=Vishnu"
  },
  {
    id: 3,
    name: "Prajwal",
    date: "31/01/2002",
    email: "prajwal@gmail.com",
    phone: "9876543213",
    nationality: "Indian",
    gender: "Male",
    age: 22,
    status: "Active",
    hire: "Intern",
    skills: "UI/UX Design, Figma, Adobe XD",
    address: "Jaipur, India",
    photo: "https://via.placeholder.com/150?text=Prajwal"
  },
  {
    id: 4,
    name: "Sujatha",
    date: "10/10/2000",
    email: "sujatha@gmail.com",
    phone: "9876543214",
    nationality: "Indian",
    gender: "Female",
    age: 28,
    status: "Active",
    hire: "Full-time",
    skills: "Cybersecurity, Ethical Hacking, Network Security",
    address: "Surat, India",
    photo: "https://via.placeholder.com/150?text=Sujatha"
  },
  {
    id: 5,
    name: "Rakshitha",
    date: "04/10/2008",
    email: "rakshitha@gmail.com",
    phone: "9876543215",
    nationality: "Indian",
    gender: "Female",
    age: 24,
    status: "Active",
    hire: "Full-time",
    skills: "Blockchain, Solidity, Web3",
    address: "Lucknow, India",
    photo: "https://via.placeholder.com/150?text=Rakshitha"
  }
];